### ISSUE TITLE
segmentation loop code

### ISSUE THREAD

**Issue by shobana1604** [thalamicseg/hipsthomasdocker#5]
**I'm constructing a loop code such that it enters all the subdirectories under the main directory and finds the file name "t1_reg.nii.gz" and runs the code. this is the code I'm using (on a windows device on Ubuntu):**
(...................:~$ #!/bin/bash

mainDir="/mnt/c/Users/..................."

for subDir in "$mainDir"/*; do
  if [ -d "$subDir" ]; then
    t1File="$subDir/t1_reg.nii.gz"

    if [ -f "$t1File" ]; then
      echo "Processing $t1File"

      docker run -v "$subDir:$subDir" -w "$subDir" --rm -t anagrammarian/thomasmerged bash -c "
        hipsthomas_csh -i t1_reg.nii.gz -t1 -big
      "
    else
      echo "Skipping $subDir: No t1_reg.nii.gz found"
    fi
  else
    echo "Skipping $subDir: Not a directory"
  fi
done)
**however I have this error constantly:**
(Killed
Completed a quick rigid affine registration of input and full template
Transform file does not exist: rigid0GenericAffine.mat
Completed transforming the mask from template space to input space
Executing: ExtractRegionFromImageByMask 3 t1_reg.nii.gz crop_t1_reg.nii.gz mask_inp.nii.gz 1 0
terminate called after throwing an instance of 'itk::ImageFileReaderException'
  what():  /src/ants/build/staging/include/ITK-5.1/itkImageFileReader.hxx:133:
 Could not create IO object for reading file mask_inp.nii.gz
The file doesn't exist.
Filename = mask_inp.nii.gz

Aborted (core dumped)
Completed cropping the input. Elapsed: 0:00:55.536607
--- Reorienting image. --- Elapsed: 0:00:55.540615
in linux
Executing: fslreorient2std crop_t1_reg.nii.gz temp/crop_t1_reg.nii.gz
ERROR: Could not find image crop_t1_reg.nii.gz
--- Correcting bias. --- Elapsed: 0:00:55.594717
Executing: N4BiasFieldCorrection -d 3 -i temp/crop_t1_reg.nii.gz -o temp/crop_t1_reg.nii.gz -b [200] -s 3 -c [50x50x30x20,1e-6]
 file temp/crop_t1_reg.nii.gz does not exist .
Segmentation fault (core dumped)
Backing input image
in linux
cp: cannot stat 'temp/crop_t1_reg.nii.gz': No such file or directory
Contrast adjusting cropped image cubic stretch
Traceback (most recent call last):
  File "/opt/thomas_new/THOMAS.py", line 504, in <module>
    main(args, temp_path, pool)
  File "/opt/thomas_new/THOMAS.py", line 304, in main
    remap_image(input_image, input_image, 3, 1, 'WM')
  File "/opt/thomas_new/libraries/remap_image.py", line 8, in remap_image
    input = nib.load(input_image)
  File "/usr/lib/python2.7/dist-packages/nibabel/loadsave.py", line 44, in load
    return guessed_image_type(filename).from_filename(filename, **kwargs)
  File "/usr/lib/python2.7/dist-packages/nibabel/loadsave.py", line 76, in guessed_image_type
    with BinOpener(filename) as fobj:
  File "/usr/lib/python2.7/dist-packages/nibabel/openers.py", line 120, in __init__
    self.fobj = opener(fileish, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/nibabel/openers.py", line 63, in _gzip_open
    gzip_file = BufferedGzipFile(fileish, *args, **kwargs)
  File "/usr/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: 'temp/crop_t1_reg.nii.gz'
mkdir: cannot create directory ‘left’: File exists
cp: No match.
mv: No match.
mv: No match.
mv: No match.
mv: No match.
mv: No match.
mv: No match.
mv: No match.
mv: No match.
mv: No match.
mv: No match.
mv: No match.
mv: cannot stat 'temp/registered.nii.gz': No such file or directory
mv: cannot stat 'left/t1_reg.nii.gz': No such file or directory
cp: cannot stat '5-VLa.nii.gz': No such file or directory
cp: cannot stat 'm5-VLa.nii.gz': No such file or directory
Using default - suffix for input labels
Fusing 2-*
Cannot open volume 2-* for reading!
Fusing 4-*
Cannot open volume 4-* for reading!
 file junk.nii.gz does not exist .
 file junk2.nii.gz does not exist .
Segmentation fault (core dumped)
Fusing 5-*
Cannot open volume 5-* for reading!
 file junk.nii.gz does not exist .
 file junk2.nii.gz does not exist .
Segmentation fault (core dumped)
Fusing 6-*
Cannot open volume 6-* for reading!
 file junk.nii.gz does not exist .
 file junk2.nii.gz does not exist .
Segmentation fault (core dumped)
Fusing 7-*
Cannot open volume 7-* for reading!
 file junk.nii.gz does not exist .
 file junk2.nii.gz does not exist .
Segmentation fault (core dumped)
Fusing 8-*
Cannot open volume 8-* for reading!
 file junk.nii.gz does not exist .
 file junk2.nii.gz does not exist .
Segmentation fault (core dumped)
Fusing 9-*
Cannot open volume 9-* for reading!
 file junk.nii.gz does not exist .
 file junk2.nii.gz does not exist .
Segmentation fault (core dumped)
Fusing 10-*
Cannot open volume 10-* for reading!
 file junk.nii.gz does not exist .
 file junk2.nii.gz does not exist .
Segmentation fault (core dumped)
Fusing 11-*
Cannot open volume 11-* for reading!
 file junk.nii.gz does not exist .
 file junk2.nii.gz does not exist .
Segmentation fault (core dumped)
Fusing 12-*
Cannot open volume 12-* for reading!
 file junk.nii.gz does not exist .
 file junk2.nii.gz does not exist .
Segmentation fault (core dumped)
Fusing 13-*
Cannot open volume 13-* for reading!
 file junk.nii.gz does not exist .
 file junk2.nii.gz does not exist .
Segmentation fault (core dumped)
Fusing 14-*
Cannot open volume 14-* for reading!
 file junk.nii.gz does not exist .
 file junk2.nii.gz does not exist .
Segmentation fault (core dumped)
mv: cannot stat 'junk.nii.gz': No such file or directory
rm: cannot remove 'junk2.nii.gz': No such file or directory
Output written to thomas.nii.gz
terminate called after throwing an instance of 'itk::ImageFileReaderException'
  what():  /src/ants/build/staging/include/ITK-5.1/itkImageFileReader.hxx:133:
 Could not create IO object for reading file thomas.nii.gz
The file doesn't exist.
Filename = thomas.nii.gz

Aborted (core dumped)
Transform file does not exist: t1_reg1InverseWarp.nii.gz
regn.nii.gz does not exist.
cp: cannot stat '../temp/bcrop_t1_reg.nii.gz': No such file or directory
foreach: No match.)

**Comment by anagrammarian** [comment]
Thomas has to run inside each subdirectory. So you need to do cd $subDir and then call docker 

docker run -v ${PWD}:${PWD} -w ${PWD} --user $(id -u):$(id -g) --rm -t anagrammarian/thomasmerged bash -c "hipsthomas_csh  -i t1_reg.nii.gz -t1 -big" 
and then cd ..

So add cd $subDir and cd .. in your if loop and it will work. Right now, you are calling t1_reg from a level above and it is not finding it.
